name: WaveSight Workflow
on:
  push:
    branches: [ main ]
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm i
          npm run start