name: WaveSight Workflow
on:
  push:
    branches: [ main ]
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: |
          npm install
          npm run start
