name: WaveSight
on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
       - run: npm install
       - run: npm run start